#THIS DOESNT WORK ON LINUIX BECAUSE FILE WAS CREATED IN DOS FORMAT
#MUST COPY PASTE IN LINUX ENVIRONMENT AND THEN IT WILL RUN APPROPRIATELY

#!/bin/bash

cd "/home/niryo/catkin_ws/devel"
python niryo_one_example_python_api.py
