# Generated by Django 2.2.2 on 2019-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboIF', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='robot',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='robot',
            name='name',
            field=models.CharField(default='Terminator', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robot',
            name='status',
            field=models.CharField(choices=[('OFF', 'OFFLINE'), ('ON', 'ONLINE'), ('CAL', 'CALIBRATING'), ('ERR', 'ERROR')], default='OFF', max_length=15),
            preserve_default=False,
        ),
    ]
