# Generated by Django 2.2.2 on 2019-06-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roboIF', '0002_auto_20190612_0847'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='warehouse',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='robot',
            name='location',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='robots',
        ),
        migrations.AddField(
            model_name='robot',
            name='warehouse_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='roboIF.WareHouse'),
            preserve_default=False,
        ),
    ]
