# Generated by Django 2.2.2 on 2019-06-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboIF', '0003_auto_20190624_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='warehouse_id',
        ),
        migrations.AddField(
            model_name='robot',
            name='location',
            field=models.CharField(default=';', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='robots',
            field=models.ManyToManyField(to='roboIF.Robot'),
        ),
    ]
