# Generated by Django 2.2.2 on 2019-06-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboIF', '0007_auto_20190626_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementrequest',
            options={'ordering': ['uid', 'robot_to_send', 'executed']},
        ),
        migrations.AddField(
            model_name='movementrequest',
            name='executed',
            field=models.BooleanField(default=False),
        ),
    ]
